<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tuks')->insert([
            [
                'kode' => 'TUK AST',
                'nama' => 'TUK Sewaktu Acarya Sinergi Teknodukasi',
                'alamat' => 'Jl. Inti IBlok C1/7, Lippo Cikarang, Bekasi 17550 Kota Bekasi, Jawa Barat',
                'no_hp' => null,
                'email' => null,
                'provinsi' => null,
                'kabupaten' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK BI',
                'nama' => 'TUK Sewaktu Bintang Indonesia - Medan',
                'alamat' => 'Jl. Garu 2A No. 44D Kota Medan, Sumatera Utara',
                'no_hp' => '081263746772',
                'email' => 'satryayudhawibowo@gmail.com',
                'provinsi' => 'SUMATERA UTARA',
                'kabupaten' => 'KOTA MEDAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK Cepit',
                'nama' => 'TUK Sewaktu Cepit',
                'alamat' => 'Jl. Bangmalang No. 5 Ruang 202 - 204, RT 56, Diro, Pendowoharjo, Sewon, Bantul, Daerah Istimewa Yogyakarta',
                'no_hp' => null,
                'email' => null,
                'provinsi' => null,
                'kabupaten' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK D Hotel',
                'nama' => 'TUK Sewaktu D Hotel',
                'alamat' => 'Jl. Sultan Agung No. 3, Setia Budi Kota Administrasi Jakarta Selatan, DKI Jakarta',
                'no_hp' => null,
                'email' => null,
                'provinsi' => null,
                'kabupaten' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK KP2TEL',
                'nama' => 'TUK Sewaktu KP2TEL Semarang',
                'alamat' => 'Telkom Johar Semarang, Jl. Arif Rahman Hakim No.1 Kel. Kauman, Kec. Semarang Tengah',
                'no_hp' => null,
                'email' => null,
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Kota Semarang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK LPK Kibar M',
                'nama' => 'TUK Sewaktu LPK Kibar Madani',
                'alamat' => 'Tiban Housing Blok B4 No. 10 - 11 Tiban Baru, Sekupang Kota Batam, Kepulauan Riau',
                'no_hp' => null,
                'email' => null,
                'provinsi' => null,
                'kabupaten' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK PSA',
                'nama' => 'TUK Sewaktu Pena Semesta Academy',
                'alamat' => 'Sukorejo 59, RT 05 RW 02, Buduran Sidoarjo, Jawa Timur',
                'no_hp' => null,
                'email' => null,
                'provinsi' => null,
                'kabupaten' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK DAA',
                'nama' => 'TUK Sewaktu Divine ARich Academy',
                'alamat' => 'Jl. Sedap Malam 1 Komp. Griya Sako Permai (GSP) Blok PP. No. 2, RT 30, RW 06, Kelurahan Sako Baru, Kecamatan Sako',
                'no_hp' => '0816382900',
                'email' => 'aderupawann@gmail.com',
                'provinsi' => 'Sumatera Selatan',
                'kabupaten' => 'Kota Palembang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK HSC',
                'nama' => 'TUK Sewaktu Hotel Sofyan Cut Mutia Menteng',
                'alamat' => 'Jl. Cut Mutia No.9, Cikini, Kec. Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10330',
                'no_hp' => '+62 819-806-140',
                'email' => null,
                'provinsi' => 'DKI',
                'kabupaten' => 'Jakarta Pusat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUKDHP',
                'nama' => 'TUK Sewaktu Daima Hotel Padang',
                'alamat' => 'Jl. Jend. Sudirman No.17, Kp. Jao, Kec. Padang Bar., Kota Padang, Sumatera Barat 25112',
                'no_hp' => '0819806140',
                'email' => 'martelusiati@gmail.com',
                'provinsi' => 'Sumatera Barat',
                'kabupaten' => 'Kota Padang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK P2SDM Batam',
                'nama' => 'TUK P2SDM Batam',
                'alamat' => 'Kantor P2SDM LPK Tunaskarya Indoswasta Ruko Taman Niaga Blok D No.2-3, Sukajadi Batam',
                'no_hp' => '08117009029',
                'email' => 'riko.jayasaputra@tunaskaryaindoswasta.com',
                'provinsi' => 'KEPULAUAN RIAU',
                'kabupaten' => 'KOTA BATAM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUKHPT',
                'nama' => 'TUK Sewaktu @Hom Premiere Timoho',
                'alamat' => 'Jl. Ipda Tut Harsono No.24, Muja Muju, Kec. Umbulharjo, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55165',
                'no_hp' => '081364725451',
                'email' => 'tukhpty@gmail.com',
                'provinsi' => 'Daerah Istimewa Yogy',
                'kabupaten' => 'Yogyakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK KMY',
                'nama' => 'Kibar Madani Yogyakarta',
                'alamat' => 'Yudonegaran GM 2 / 212, RT 02, RW 01, Kel. Prawirodirjan, Kemantren Gondomanan',
                'no_hp' => '081364715451',
                'email' => 'kibarmadaniyogyakarta@gmail.com',
                'provinsi' => 'DI YOGYAKARTA',
                'kabupaten' => 'KOTA YOGYAKARTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUKAHM',
                'nama' => 'TUK Abadi Hotel Malioboro',
                'alamat' => 'Jl. Ps. Kembang No.49, Sosromenduran, Gedong Tengen, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55271',
                'no_hp' => '081364715451',
                'email' => 'mohbadaruddinhadi@gmail.com',
                'provinsi' => 'DI YOGYAKARTA',
                'kabupaten' => 'KOTA YOGYAKARTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK ASAI',
                'nama' => 'TUK Aya Sophia Academy Indonesia',
                'alamat' => 'Cluster Jesisca 1 Blok D No 8-9, Sukamulya, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
                'no_hp' => '081380993677',
                'email' => null,
                'provinsi' => 'BANTEN',
                'kabupaten' => 'KAB. TANGERANG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK CA',
                'nama' => 'TUK Character Academy',
                'alamat' => 'Kemang Ifi Graha Jalan Jakarta A9/8A Kelurahan Jatirasa, Kecamatan Jatiasih, Kota Bekasi 17424 (021) 8240.4112',
                'no_hp' => '08129358585',
                'email' => null,
                'provinsi' => 'JAWA BARAT',
                'kabupaten' => 'KOTA BEKASI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK NCU',
                'nama' => 'TUK Nayata Corporate University',
                'alamat' => 'Komuka Coffee Shop Perumahan Metland Menteng Blok F4 No.10 RT 001/RW 007 Kelurahan Ujung Menteng, Kecamatan Cakung, 13960',
                'no_hp' => '081808972013',
                'email' => null,
                'provinsi' => 'DKI JAKARTA',
                'kabupaten' => 'KOTA ADM. JAKARTA TI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK SGPI',
                'nama' => 'TUK Sinergi Gaya Potenza Indonesia',
                'alamat' => 'Jl. Gurun Laweh no 4A, RT 02/RW 05, Kel. Gurun Laweh nan XX, Kec. Lubuk Begalung, Kota Padang, Sumatera Barat 25221',
                'no_hp' => '082386999009',
                'email' => null,
                'provinsi' => 'SUMATERA BARAT',
                'kabupaten' => 'KOTA PADANG SIDEMPUA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TNT',
                'nama' => 'TUK Hotel Muara Ternate',
                'alamat' => 'Jl. Merdeka No.19, Gamalama, Kec. Ternate Tengah, Kota Ternate, Maluku Utara',
                'no_hp' => '0819806140',
                'email' => 'tukternatetki@gmail.com',
                'provinsi' => 'MALUKU UTARA',
                'kabupaten' => 'KOTA TERNATE TERNATE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'TUK Parikesit',
                'nama' => 'TUK Parikesit Yogyakarta',
                'alamat' => 'Dinsosnakertrans Kota Yogyakarta, Walikota Yogyakarta, Jl. Kenari No.56, Muja Muju, Kec. Umbulharjo, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55165',
                'no_hp' => '081364715451',
                'email' => 'tukparikesit@gmail.com',
                'provinsi' => 'DI YOGYAKARTA',
                'kabupaten' => 'KOTA YOGYAKARTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
